import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    int id;
    public Editor() {}

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
        id = 0;
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
        int postid = Integer.parseInt(request.getParameter("postid"));
        if(request.getParameter("action").equals("open")){
          String postTitle = "";
          String postBody = "";
          if(postid <= 0){
            postTitle = request.getParameter("title");
            postBody = request.getParameter("body");
          }
          else{
            Connection con = null;
            Statement stmt = null;
            ResultSet rs = null;
            try{
              Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
              stmt = con.createStatement();
              //String query = "SELECT * FROM Posts WHERE postid=" + Integer.toString(postid);
              rs = stmt.executeQuery("SELECT * FROM Posts WHERE postid=" + Integer.toString(postid));
              rs.next();
              postTitle = rs.getString(3);
              postBody = rs.getString(4);
              //postTitle = query;
            }catch(SQLException se){
            //Handle errors for JDBC
              se.printStackTrace();
            }catch(Exception e){
            //Handle errors for Class.forName
              e.printStackTrace();
            }finally{
              try { rs.close(); } catch (Exception e) { /* ignored */ }
              try { con.close(); } catch (Exception e) { /* ignored */ }
            }
          }
          request.setAttribute("ptitle", postTitle);
          request.setAttribute("pbody", postBody);
          request.getRequestDispatcher("/edit.jsp").forward(request, response);
        }
        else{
          Connection con = null;
          //Statement stmt = null;
          PreparedStatement ps = null;
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
            ps = con.prepareStatement("DELETE FROM Posts WHERE postid = ? AND username = ?");
            ps.setInt(1, postid);
            ps.setString(2, request.getParameter("username"));
            ps.executeUpdate();
          }catch(SQLException se){
        //Handle errors for JDBC
            se.printStackTrace();
          }catch(Exception e){
         //Handle errors for Class.forName
            e.printStackTrace();
          }finally{
            try { ps.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
          }
        request.getRequestDispatcher("/list.jsp").forward(request, response);
        }
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
      Connection con = null;
      Statement stmt = null;
      PreparedStatement ps = null;
      int postid = Integer.parseInt(request.getParameter("postid"));
      String name = request.getParameter("username");
      if(request.getParameter("action").equals("save")){
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        Date time = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String modified = sdf.format(time);
        if(postid <= 0){
          String created = sdf.format(time);
          id++;
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
            stmt = con.createStatement();
            String sqlString = "INSERT INTO Posts VALUES('" + name + "', " 
                              +  Integer.toString(id) + ", "
                              + "'" + title + "', "
                              + "\"" + body + "\", "
                              + "'" + modified + "', "
                              + "'" + created + "')";
            stmt.executeUpdate(sqlString);
          }catch(SQLException se){
          //Handle errors for JDBC
            se.printStackTrace();
          }catch(Exception e){
           //Handle errors for Class.forName
            e.printStackTrace();
          }finally{
            try { con.close(); } catch (Exception e) { /* ignored */ }
          } 
        }
        else{
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
            ps = con.prepareStatement("UPDATE Posts SET title = ?, body = ?, modified = ? WHERE postid = ? AND username = ?");
            ps.setString(1, title);
            ps.setString(2, body);
            ps.setString(3, modified);
            ps.setInt(4, postid);
            ps.setString(5, name);
            ps.executeUpdate();
          }catch(SQLException se){
          //Handle errors for JDBC
            se.printStackTrace();
          }catch(Exception e){
           //Handle errors for Class.forName
            e.printStackTrace();
          }finally{
            try { ps.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
          } 
        }
    		request.getRequestDispatcher("/list.jsp").forward(request, response);
      }
      else if(request.getParameter("action").equals("preview")){
      		Parser parser = Parser.builder().build();
      		HtmlRenderer renderer = HtmlRenderer.builder().build();
      		String ptitle = renderer.render(parser.parse(request.getParameter("title")));
      		String pbody = renderer.render(parser.parse(request.getParameter("body")));
      		request.setAttribute("ptitle", ptitle);
      		request.setAttribute("pbody", pbody);
    		request.getRequestDispatcher("/preview.jsp").forward(request, response);
      }
      else if(request.getParameter("action").equals("close")){
        request.getRequestDispatcher("/list.jsp").forward(request, response);
      }
      else {
        if(postid > 0){
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
            ps = con.prepareStatement("DELETE FROM Posts WHERE postid = ? AND username = ?");
            ps.setInt(1, postid);
            ps.setString(2, request.getParameter("username"));
            ps.executeUpdate();
          }catch(SQLException se){
        //Handle errors for JDBC
            se.printStackTrace();
          }catch(Exception e){
         //Handle errors for Class.forName
            e.printStackTrace();
          }finally{
            try { ps.close(); } catch (Exception e) { /* ignored */ }
            try { con.close(); } catch (Exception e) { /* ignored */ }
          }
          request.getRequestDispatcher("/list.jsp").forward(request, response);
        }
        else{
        	request.getRequestDispatcher("/list.jsp").forward(request, response);
        }
      }
    }
}

